version: '3.8'

services:
  # asp .net 8 application
  api:
    container_name: apple-mart-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - server=sqlserver-container
      - database=AppleMartDB
      - port=1433
      - dbuser=sa
      - password=YourStrongP@ssword
    depends_on:
      - sql-server
    networks:
      - sql_network

  # sql database
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongP@ssword
      - MSSQL_PID=Express
    mem_limit: 2g
    ports:
      - "1433:1433"
    networks:
      - sql_network
    volumes:
      - sqldata:/var/opt/mssql
    restart: always

networks:
  sql_network:
    driver: bridge

volumes:
  sqldata: